version: '3.8'
services:
   java-maven-app:
      image : moussbed/java-mvn:latest
      ports:
        - "8080:8080"

   postgres:
      image: postgres:13
      restart: always
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD:pwd-password-contrasena