apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
  labels:
    app: $APP_NAME
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      imagePullSecrets:
        - name: ecr-registry-key
      containers:
        - name: $APP_NAME
       #   image: "moussbed/java-mvn:${IMAGE_VERSION}"
          image: "${IMAGE_NAME}:${IMAGE_VERSION}"
          imagePullPolicy: Always # Force to pull
          ports:
            - containerPort: 8080